[build]
  command = "npm run build"
  
  [build.environment]
    NODE_VERSION = "18.20.4"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"

[functions."analyze-watchlist"]
  schedule = "0 11 * * *"
